services:
  postgres:
    image: postgres

    container_name: finlog-db

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - finlog

networks:
  finlog:
    driver: bridge
